import React, { useState } from "react";

// Android Optimizer — Single-file React component (Enhanced)
// - Uses Tailwind CSS classes (assumes Tailwind is configured in the host app)
// - Allows choosing safe, non-root tweaks and generates shell script(s)
// - Can generate multiple profile scripts with small variations and bundle as ZIP using JSZip
// - Adds: device presets for common phones (non-root-safe), device detection helper script (ADB),
//         and an ADB helper script that pushes/unzips/installs the pack to a connected device.
// - Exports a default React component so it can be previewed in the canvas

export default function AndroidOptimizer() {
  const [profileCount, setProfileCount] = useState(50);
  const [animationsOff, setAnimationsOff] = useState(true);
  const [brightness, setBrightness] = useState(150);
  const [wifiEnable, setWifiEnable] = useState(true);
  const [ioSchedHint, setIoSchedHint] = useState("deadline");
  const [generating, setGenerating] = useState(false);
  const [previewScript, setPreviewScript] = useState("");
  const [lastZipName, setLastZipName] = useState("");
  const [preset, setPreset] = useState("generic");
  const presets = {
    generic: { note: 'Generic safe non-root tweaks', io_sched: 'deadline', brightness: 150 },
    pixel6: { note: 'Google Pixel 6 (non-root suggestions only)', io_sched: 'deadline', brightness: 170 },
    samsung_s21: { note: 'Samsung S21 (non-root suggestions only)', io_sched: 'noop', brightness: 160 },
    oneplus9: { note: 'OnePlus 9 (non-root suggestions only)', io_sched: 'deadline', brightness: 180 }
  };

  function makeScript(i, variations, deviceInfo) {
    const id = String(i).padStart(4, "0");
    const animations = variations.animations ? "off" : "on";
    const bright = variations.brightness;
    const swap = variations.swap;
    const io_sched = variations.io_sched;
    const wifiEnableLine = variations.wifiEnable ? 'svc wifi enable 2>/dev/null || echo "Could not enable wifi"' : 'svc wifi disable 2>/dev/null || echo "Could not disable wifi"';

    return `#!/system/bin/sh\n# Profile: profile_${id}.sh\n# Generated by Android Optimizer UI\n# Device hint: ${deviceInfo.model || 'unknown'} (${deviceInfo.device || 'unknown'})\n\nPROFILE_NAME=\"profile_${id}\"\nANIMATIONS=\"${animations}\"\nBRIGHTNESS_HINT=${bright}\nSWAP_HINT=\"${swap}\"\nIO_SCHED_HINT=\"${io_sched}\"\n\n echo \"Running $PROFILE_NAME - animations=$ANIMATIONS brightness=$BRIGHTNESS_HINT io_sched=$IO_SCHED_HINT\"\n\nif command -v settings >/dev/null 2>&1; then\n  if [ \"$ANIMATIONS\" = \"off\" ]; then\n    settings put global window_animation_scale 0.0\n    settings put global transition_animation_scale 0.0\n    settings put global animator_duration_scale 0.0\n  else\n    settings put global window_animation_scale 1.0\n  fi\nfi\n\nif command -v settings >/dev/null 2>&1; then\n  settings put system screen_brightness $BRIGHTNESS_HINT\nfi\n\nif command -v svc >/dev/null 2>&1; then\n  ${wifiEnableLine}\nfi\n\nIO_SYSFS=\"/sys/block/mmcblk0/queue/scheduler\"\nif [ -w $IO_SYSFS ] 2>/dev/null; then\n  echo $IO_SCHED_HINT > $IO_SYSFS\nelse\n  echo \"I/O scheduler change requires root; skipped\"\nfi\n\nCPU_GOV_SYS=\"/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor\"\nif [ -w $CPU_GOV_SYS ] 2>/dev/null; then\n  echo performance > $CPU_GOV_SYS\nelse\n  echo \"CPU governor change requires root; skipped\"\nfi\n\necho \"Profile $PROFILE_NAME finished.\"\n`;
  }

  function loadJSZip() {
    return new Promise((resolve, reject) => {
      if (window.JSZip) return resolve(window.JSZip);
      const s = document.createElement("script");
      s.src = "https://cdn.jsdelivr.net/npm/jszip@3.10.1/dist/jszip.min.js";
      s.onload = () => resolve(window.JSZip);
      s.onerror = reject;
      document.head.appendChild(s);
    });
  }

  async function generateAndDownload() {
    setGenerating(true);
    try {
      const count = Math.max(1, Math.min(4500, Number(profileCount) || 1));
      const deviceInfo = { model: '', device: '', recommendation: '' };
      const chosenPreset = presets[preset] || presets.generic;

      const files = [];
      for (let i = 1; i <= count; i++) {
        const variations = {
          animations: (animationsOff ? (i % 2 === 0) : (i % 2 !== 0)),
          brightness: Math.max(10, Math.min(255, (brightness || chosenPreset.brightness) + (i % 50) - 25)),
          swap: i % 3 === 0 ? "trim_swap" : "no_swap",
          io_sched: ["noop", "deadline", "cfq", "bfq", "none"][i % 5],
          wifiEnable
        };
        const content = makeScript(i, variations, deviceInfo);
        files.push({ name: `profile_${String(i).padStart(4, "0")}.sh`, content });
      }

      const executeAll = `#!/bin/sh\nDIR=${'"$PWD"'}\nfind \"$DIR\" -type f -name \"profile_*.sh\" | while read f; do chmod +x \"$f\"; sh \"$f\"; done\n`;
      files.push({ name: "execute_all.sh", content: executeAll });

      const JSZipLib = await loadJSZip();
      const zip = new JSZipLib();
      files.forEach(f => zip.file(f.name, f.content));
      const blob = await zip.generateAsync({ type: "blob" });

      const zipName = `android_optimizer_profiles_${count}.zip`;
      setLastZipName(zipName);
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = zipName;
      document.body.appendChild(a);
      a.click();
      a.remove();
      URL.revokeObjectURL(url);
    } catch (e) {
      console.error(e);
      alert("Failed to generate ZIP: " + (e.message || e));
    } finally {
      setGenerating(false);
    }
  }

  function previewOne() {
    const deviceInfo = { model: presets[preset] ? preset : 'generic', device: presets[preset] ? preset : 'generic', recommendation: presets[preset].note };
    const variations = { animations: animationsOff, brightness: brightness || presets[preset].brightness, swap: "no_swap", io_sched: ioSchedHint, wifiEnable };
    const s = makeScript(1, variations, deviceInfo);
    setPreviewScript(s);
  }

  return (
    <div className="max-w-4xl mx-auto p-6">
      <div className="bg-white rounded-2xl shadow p-6">
        <h1 className="text-2xl font-bold mb-2">Android Optimizer (Non-root-friendly)</h1>
        <p className="text-sm text-gray-600 mb-4">Generate safe performance profile shell scripts for Android. These templates use non-root commands (settings, svc) and safely skip root-only actions.</p>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="space-y-3">
            <label className="block">
              <div className="flex justify-between text-sm"><span>Preset</span><strong>{preset}</strong></div>
              <select value={preset} onChange={e => setPreset(e.target.value)} className="w-full">
                {Object.keys(presets).map(k => <option key={k} value={k}>{k} — {presets[k].note}</option>)}
              </select>
            </label>

            <label className="flex items-center space-x-3">
              <input type="checkbox" checked={animationsOff} onChange={e => setAnimationsOff(e.target.checked)} className="w-4 h-4" />
              <span>Turn animations off</span>
            </label>

            <label className="block">
              <div className="flex justify-between text-sm"><span>Brightness hint</span><strong>{brightness}</strong></div>
              <input type="range" min="10" max="255" value={brightness} onChange={e => setBrightness(Number(e.target.value))} />
            </label>

            <label className="flex items-center space-x-3">
              <input type="checkbox" checked={wifiEnable} onChange={e => setWifiEnable(e.target.checked)} className="w-4 h-4" />
              <span>Ensure Wi-Fi enabled</span>
            </label>

            <label className="block">
              <div className="flex justify-between text-sm"><span>I/O scheduler hint</span><strong>{ioSchedHint}</strong></div>
              <select value={ioSchedHint} onChange={e => setIoSchedHint(e.target.value)} className="w-full">
                <option value="noop">noop</option>
                <option value="deadline">deadline</option>
                <option value="cfq">cfq</option>
                <option value="bfq">bfq</option>
                <option value="none">none</option>
              </select>
            </label>

            <label className="block">
              <div className="flex justify-between text-sm"><span>Number of profiles</span><strong>{profileCount}</strong></div>
              <input type="number" min="1" max="4500" value={profileCount} onChange={e => setProfileCount(Number(e.target.value))} />
            </label>
          </div>

          <div className="space-y-3">
            <button onClick={previewOne} className="px-4 py-2 bg-gray-200 rounded-lg hover:bg-gray-300 w-full">Preview Script</button>
            <button onClick={generateAndDownload} disabled={generating} className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 w-full">{generating ? 'Generating...' : 'Generate ZIP'}</button>

            {lastZipName && <p className="text-sm text-green-600">Generated: {lastZipName}</p>}

            {previewScript && (
              <pre className="bg-gray-900 text-green-400 text-xs p-3 rounded-lg overflow-x-auto max-h-80 whitespace-pre-wrap">{previewScript}</pre>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}